spring.application.name=backend

#Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/act_ecom
spring.datasource.username=postgres
spring.datasource.password=07132002
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update