spring.application.name=backend

#Frontend
app.cors.allowed-origins=http://localhost:4200

#Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/act_ecom
spring.datasource.username=postgres
spring.datasource.password=07132002
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#Cipher Configuration
cipher.algorithm=AES
cipher.key=Th3W0r!dbE!0n9$T0g1@2etH3tr*eg0E

#JWT
jwt.secret=4c9d5d3f7f9b4b2e91c6e8a4d7f2b5c1a9e3f6d8b2c4e7f1a5d9c3b6e8f2a4d1


server.servlet.context-path=/api